# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/psp2',
                'doc_host': 'https://helmenov.github.io',
                'git_url': 'https://github.com/helmenov/psp2',
                'lib_path': 'psp2'},
  'syms': {'psp2.core': {'psp2.core.foo': ('core.html#foo', 'psp2/core.py')}}}
